language: csharp
solution: GeUtilities.sln
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
  - nuget restore GeUtilities.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
- dotnet build
- dotnet test GeUtilities.Tests/GeUtilities.Tests.csproj
