os:
    - linux
matrix:
    include:
        -
            dotnet: 3.0
            install: ['dotnet restore']
            language: csharp
            mono: none
            script: ['dotnet build', 'dotnet test GeUtilities.Tests/GeUtilities.Tests.csproj']
            solution: GeUtilities.sln
