version: '2.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - dotnet restore
build:
  verbosity: minimal
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore GeUtilities.Tests\GeUtilities.Tests.csproj --verbosity m
  - cmd: dotnet test GeUtilities.Tests\GeUtilities.Tests.csproj
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\GeUtilities.Tests\bin\Debug\netcoreapp2.0\GeUtilities.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[GeUtilities.Tests*]*" -output:".\GeUtilities_coverage.xml"
  - codecov -f "GeUtilities_coverage.xml"
on_finish :
  # any cleanup in here
deploy: off
