version: '2.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - dotnet restore
build:
  verbosity: minimal
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore GeUtilities.Tests\GeUtilities.Tests.csproj --verbosity m
  - cmd: dotnet test GeUtilities.Tests\GeUtilities.Tests.csproj
  - OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:".\GeUtilities.Tests\bin\Debug\netcoreapp2.0\GeUtilities.Tests.dll -noshadow" -filter:"+[*]* -[GeUtilities.Tests*]*" -oldStyle -output:".\GeUtilities_coverage.xml"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "GeUtilities_coverage.xml" -t ab819306-5320-4cea-a2c8-cded1183d1d4
on_finish :
  # any cleanup in here
deploy: off
